# QUITAR .ENV DE REPO

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ${HOME}/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ${HOME}/data/mariadb
      o: bind
      type: none

services:
  nginx:
    container_name: nginx
    image: inception-nginx
    build:
      context: requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      inception:
        aliases:
          - nginx
    env_file: .env
    restart: always
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: inception-wordpress
    build:
      context: requirements/wordpress
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        WP_NAME: ${WP_NAME}
        WP_DATABASE: ${WP_DATABASE}
        WP_USER: ${WP_USER}
        WP_PASSWORD: ${WP_PASSWORD}
        WP_EMAIL: ${WP_EMAIL}
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    volumes:
      - wordpress:/var/www/html
      - mariadb:/var/lib/mysql
    networks:
      inception:
        aliases:
          - wordpress
    env_file: .env
    restart: always
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb-wordpress
    build:
      context: requirements/mariadb
      args:
        WP_DATABASE: ${WP_DATABASE}
        WP_USER: ${WP_USER}
        WP_PASSWORD: ${WP_PASSWORD}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      inception:
        aliases:
          - mariadb
    env_file: .env
    restart: always
    
networks:
  inception:
    name: inception