services:
  nginx:
    container_name: nginx
    image: inception-nginx
    build:
      context: requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "443:443"
    networks:
      inception:
        aliases:
          - nginx
    env_file: .env
    restart: always
  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: inception-wordpress
    build:
      context: requirements/wordpress
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        WP_NAME: ${WP_NAME}
        WP_DATABASE: ${WP_DATABASE}
        WP_USER: ${WP_USER}
        WP_PASSWORD: ${WP_PASSWORD}
        WP_EMAIL: ${WP_EMAIL}
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    networks:
      inception:
        aliases:
          - wordpress
    env_file: .env
    restart: always
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb-wordpress
    build:
      context: requirements/mariadb
      args:
        WP_DATABASE: ${WP_DATABASE}
        WP_USER: ${WP_USER}
        WP_PASSWORD: ${WP_PASSWORD}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
    networks:
      inception:
        aliases:
          - mariadb
    env_file: .env
    restart: always
    
networks:
  inception:
    name: inception



# TO-DO LIST
#   - Añadir DOMAIN_NAME a /etc/hosts de VM