services:
  nginx:
    container_name: nginx
    image: inception-nginx:latest
    build:
      context: requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "443:443"
    networks:
      - inception
    env_file: .env
    restart: always
    
networks:
  inception:
    name: inception