services:
  nginx:
    image: inception-nginx:latest
    build:
      context: requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "443:443"
      - "9000:9000"
    networks:
      - inception
    env_file: .env
    
networks:
  inception:
    name: inception