services:
  nginx:
    image: inception-nginx:latest
    build:
      context: requirements/nginx
    ports:
      - "443:443"
      - "9000:9000"
    networks:
      - inception
    secrets:
      - DOMAIN_NAME
    

networks:
  inception:
    name: inception

secrets:
  DOMAIN_NAME:
      environment: "DOMAIN_NAME"