# QUITAR .ENV DE REPO

networks:
  inception:
    name: inception


volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ${HOME}/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ${HOME}/data/mariadb
      o: bind
      type: none
  socket:
    name: socket
    driver: local
    driver_opts:
      device: ${HOME}/data/socket
      o: bind
      type: none


services:
  nginx:
    container_name: nginx
    image: inception-nginx
    build:
      context: requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      inception:
        aliases:
          - nginx
    env_file: .env
    restart: always
    depends_on:
      - wordpress
  
  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: inception-wordpress
    build:
      context: requirements/wordpress
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        WP_NAME: ${WP_NAME}
        WP_DATABASE: ${WP_DATABASE}
        WP_USER: ${WP_USER}
        WP_PASSWORD: ${WP_PASSWORD}
        WP_EMAIL: ${WP_EMAIL}
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    volumes:
      - wordpress:/var/www/html
      - mariadb:/var/lib/mysql
      - socket:/var/run/redis
    networks:
      inception:
        aliases:
          - wordpress
    env_file: .env
    restart: always
    depends_on:
      - mariadb

  redis:
    container_name: redis
    image: inception-redis
    build:
      context: requirements/redis
    volumes:
    - socket:/var/run/redis
    networks:
      inception:
        aliases:
          - redis
    env_file: .env
    restart: always
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb-wordpress
    build:
      context: requirements/mariadb
      args:
        WP_DATABASE: ${WP_DATABASE}
        WP_USER: ${WP_USER}
        WP_PASSWORD: ${WP_PASSWORD}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      inception:
        aliases:
          - mariadb
    env_file: .env
    restart: always

  ftp:
    container_name: ftp
    image: inception-ftp
    build:
      context: requirements/ftp
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASSWORD: ${FTP_PASSWORD}
    volumes:
      - wordpress:/home/${FTP_USER}/ftp/files
    ports:
      - "20:20"
      - "21:21"
      - "40000-40005:40000-40005"
    networks:
      inception:
        aliases:
          - ftp
    env_file: .env
    restart: always
    depends_on:
      - wordpress