services:
  nginx:
    container_name: nginx
    image: inception-nginx:latest
    build:
      context: requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "443:443"
      - "9000:9000"
    networks:
      - inception
    env_file: .env
    restart: always
  wordpress:
    container_name: wordpress
    image: inception-wordpress:latest
    build:
      context: requirements/wordpress
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "9000:9000"
      - "3306:3306"
    networks:
      - inception
    env_file: .env
    restart: always
    
networks:
  inception:
    name: inception